### ISSUE TITLE
MessageProviders should catch cloning errors 

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#100]
Related to https://github.com/aragon/aragon-apps/issues/193 (most likely cause of it).

Similar to https://github.com/apollographql/apollo-client-devtools/issues/64.

We should definitely catch these errors (via `err instanceof DOMException && (err.message.indexOf('could not be cloned' !== -1))`) to make sure we don't blow up the entire execution context (e.g. the messenger along with what seems to be the web3 instance). Confirmed on Chrome and Firefox.

**Comment by onbjerg** [comment]
This error should be fixed now
