### ISSUE TITLE
Gracefully handle errors in Radspec

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#101]
1. Ignore error and provide a default message
2. Log error to console
3. ???
4. Profit

**Comment by izqui** [comment]
5. ANT moon

**Comment by Quazia** [comment]
Low priority currentl

**Comment by Quazia** [comment]
If a description key is not provided, we can provide an error message saying that a description needs to be provided. This should _not_ throw, but instead return a transaction with enough information for the front end to attach it's own description in place of radspec.
