### ISSUE TITLE
Inheritance within multiple files

### ISSUE THREAD

**Issue by max-cote** [aragon/aragon.js#118]
When I write a simple app with 2 contracts, one inheriting the other and the 2 are in separate files, let's say :

CounterApp.sol:

```javascript
pragma solidity ^0.4.4;

import "@aragon/os/contracts/apps/AragonApp.sol";
import "./Parent.sol";

contract CounterApp is AragonApp, Parent {  

}
```

Parent.sol:

```javascript
pragma solidity ^0.4.4;

contract Parent {
    event ParentValueChange(address indexed entity, uint value);

    uint public parentValue;

    function setNewParentValue(uint val) external {
        parentValue = val;
        ParentValueChange(msg.sender, parentValue);
    }
}
```

Nothing seems to happen when `app.setNewParentValue(2)` is called in `App.js`. There are also no errors in the dev console.

**Yet if the contracts are in the same file, everything works:**

```javascript
pragma solidity ^0.4.4;

contract Parent {
    event ParentValueChange(address indexed entity, uint value);

    uint public parentValue;

    function setNewParentValue(uint val) external {
        parentValue = val;
        ParentValueChange(msg.sender, parentValue);
    }
}

contract CounterApp is AragonApp, Parent {  

}
```
I made the example available here to reproduce the issue: https://github.com/max-cote/aragon-inheritance
Is this the expected behavior?
I'm on Ubuntu with Node v8.11.1. Using Chrome 66.

Thanks!

**Comment by sohkai** [comment]
@max-cote Been thinking about this for a bit and it occurred to me today why this is happening.

Unfortunately, our CLI is not good at understanding inherited contracts to generate their ABIs; it's pretty flaky right now. All of our own apps' contracts define their "outside" interface for their frontends in a single contract.

To get around this, please put all logic you'd like to access in aragon.js in a single contract for now. We'll improve the tooling around this at a later point so this is less awkward and surprising: https://github.com/aragon/aragon-cli/issues/133

**Comment by max-cote** [comment]
Thanks @sohkai ! Yeah I didn't know if this belonged to aragon.js or aragon-cli. Maybe we'll give a shot at this issue as well! ;)

**Comment by sohkai** [comment]
@max-cote That would be awesome!

**Comment by cslarson** [comment]
Just ran in to this issue myself. Good to know it's a known issue.
