### ISSUE TITLE
Add ability for frontend to trigger events in the script

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#119]
It'd be great if there was a way for the frontend to send arbitrary events to the script, and define logic in the script to handle it.

It could look like `app.trigger('<event name>', <event params...>)` from the frontend, and `@aragon/client`'s `app.store()` could receive these as-is.

See https://github.com/aragon/aragon.js/pull/313#issuecomment-496577875 for an description of how this could potentially be done.

**Comment by 2color** [comment]
That's an interesting idea. Can you give an example of a use-case?

**Comment by sohkai** [comment]
A few come to mind:

- Fetching more data (if, in the future, reducing all of the state takes too long)
- Triggering an external API call that is better handled as part of the webworker
- Optimistic UI for actions (multiple ways to do this, but "triggering" an "optimistic" event in the script could be one way)
