### ISSUE TITLE
Add application dev environment setup guide

### ISSUE THREAD

**Issue by izqui** [aragon/aragon.js#13]

**Comment by onbjerg** [comment]
What would you specifically like to know?

**Comment by izqui** [comment]
Basic instructions for how to run it. I remember you said something about a mock wrapper you were using to test it.

**Comment by onbjerg** [comment]
Ah, okay, so for building apps, not for contributing to `node-aragon`?

**Comment by izqui** [comment]
Yes!

**Comment by onbjerg** [comment]
Okay, thanks for clarifying Jorge 😊

**Comment by sohkai** [comment]
Closing given the current state of our CLI :)
