### ISSUE TITLE
Add artifacts for Kernel and EVMScriptRegistry

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#132]
`aragon.js` should contain default artifacts for `aragonOS`-specific functionality and apps, like the `Kernel`, `ACL`, and `EVMScriptRegistry` so that clients can retrieve information for them just like a normal app.

In particular, the role hashes would be nice :).

**Comment by sohkai** [comment]
ACL artifacts were added in #138.

**Comment by bpierre** [comment]
It would also be useful to have a flag like `isCoreApp` for ACL and EVMScriptRegistry.
