### ISSUE TITLE
Implement transaction pathing for actions without roles

### ISSUE THREAD

**Issue by izqui** [aragon/aragon.js#134]
Right now transaction pathing can only calculate paths if the action that the user wants to perform has a role. There are other instances in which the user can or cannot perform an action, but wants to perform it through a forwarder that they have access to.

An example for this may be voting by using a forwarder as required by this DAO design: https://github.com/aragon/governance/issues/32. In that case an ANT holder won't have any voting power in the main 'Proposal Voting app' so the voting action would need to be forwarded to the 'ANT Veto' voting app.

**Comment by sohkai** [comment]
I believe this should be achievable with the "finalForwarder" concept introduced for the ACL, but needs a bit of code changes (we right now assume that every intent destination is going to be an installed app).

**Comment by sohkai** [comment]
Closing; the `finalForwarder` option should be used for most cases. We will not be supporting more advanced use cases for now.
