### ISSUE TITLE
Add provider engine

### ISSUE THREAD

**Issue by jvluso** [aragon/aragon.js#145]
A provider engine would allow forwarder accounts in a DAO to be used as an account by truffle. It would also allow commands to be sent through multiple DAOs. The provider should be a web3 provider that takes the following arguments:

- Another web3 provider which all requests are sent to for reading the blockchain
- The dao that the app in question is a part of
- The app that all commands will finally be forwarded out of

Adding this to a truffle configuration should allow a user to interact with the rest of the blockchain using truffle commands as if the chosen app was their account. They should be able to publish aragon apps, update aragon apps, and vote in other daos.It should also be possible to chain multiple of these providers together, and still be able to perform all necessary functions.

**Comment by Quazia** [comment]
This might be a lot to do in a single issue, it might make sense to make this new package an epic and then add sub-tasks?
