### ISSUE TITLE
Have a way to access the roles of accounts

### ISSUE THREAD

**Issue by asoltys** [aragon/aragon.js#162]
It would be useful to be able to determine what roles various accounts have so that UI elements can be displayed or hidden accordingly.

**Comment by izqui** [comment]
Having access to this information will be so useful for apps!

The queries that would be interesting to support are:
- Does any account in a set of accounts have a particular role? (should also return accounts that could eventually perform the action by [forwarding](https://hack.aragon.org/docs/forwarding-intro.html))
- Does anyone have the role? Even if the action cannot be performed by the current user, it would be interesting to show the action in the UI to signal that the action can be done. If the action cannot be done, then it can be completely hidden.

**Comment by sohkai** [comment]
Closing, as technically this is possible today by using the `installedApps()` API; you can find the ACL and ask it for information directly.

That being said, we may evaluate a more streamlined API in the future for checking account permissions.
