### ISSUE TITLE
transactions fail if they can be pathed directly

### ISSUE THREAD

**Issue by jvluso** [aragon/aragon.js#169]
as title

**Comment by sohkai** [comment]
@jvluso are you using the version on master? We need to apply #164, although that shouldn't have affected direct paths.

**Comment by jvluso** [comment]
We were using the most recent version on npm. I'm not sure that this was the problem that we were having. I'll look into this more this week.

**Comment by sohkai** [comment]
Gotcha, the current release on npm doesn't include the changes to the gas price anyway so it won't be related to the fixes included in #164.

**Comment by jvluso** [comment]
I think this has been resolved.
