### ISSUE TITLE
Add ability for apps to get current list of apps

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#194]
It'd be nice if apps had information about what apps were currently installed, as well as information about themselves (e.g. address and identifier).

**Comment by bpierre** [comment]
> about what apps were currently installed

Do we want any app to know about the other apps that are currently installed? I’m wondering if this could have any security implications.

**Comment by sohkai** [comment]
_Technically_ they would know anyway, since it's all public info they could get from the ACL on-chain. Even if other apps knew about each other, our security model should still be kept if we make sure to explicitly warn about any interaction between apps—if you try to do an action on an app but the transaction's actually to another contract / app, the Aragon client should warn you about it and make sure you know what you're doing.
