### ISSUE TITLE
Refactor using morphisms/middlewares/hooks

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon.js#215]
There are some pretty big functions in the wrapper code that should be broken into pieces and moved to their directories.

<details>
<summary>Example: calculateTransactionPath</summary>

```js
async calculateTransactionPath (sender, destination, methodName, params, finalForwarder) {
   const finalForwarderProvided = isAddress(finalForwarder)

    const permissions = await this.permissions.take(1).toPromise()
    const app = await this.getApp(destination)

    if (!app) {
      throw new Error(`No artifact found for ${destination}`)
    }

    const jsonInterface = app.abi
    if (!jsonInterface) {
      throw new Error(`No ABI specified in artifact for ${destination}`)
    }

    const methodABI = app.abi.find(
      (method) => method.name === methodName
    )
    if (!methodABI) {
      throw new Error(`${methodName} not found on ABI for ${destination}`)
    }

    let transactionOptions = {}

    // If an extra parameter has been provided, it is the transaction options if it is an object
    if (methodABI.inputs.length + 1 === params.length && typeof params[params.length - 1] === 'object') {
      const options = params.pop()
      transactionOptions = { ...transactionOptions, ...options }
    }

    // The direct transaction we eventually want to perform
    const directTransaction = {
      ...transactionOptions, // Options are overwriten by the values below
      from: sender,
      to: destination,
      data: this.web3.eth.abi.encodeFunctionCall(methodABI, params)
    }

    if (transactionOptions.token) {
        // another chunk of code
    }

    // rest of the code...
}
```
</details>

Could be refactored into something like this:

<details>
<summary>Solution A: imperative</summary>

```js
async calculateTransactionPath (sender, destination, methodName, params, finalForwarder) {
    const finalForwarderProvided = isAddress(finalForwarder)

    const permissions = await this.permissions.take(1).toPromise()
    const app = await this.getApp(destination)

    if(!validateAppAndMethod(app, methodName)) {
        throw new Error('Something went wrong')
    }

    let transactionOptions = extractTransactionOptions(params, methodABI)

    // The direct transaction we eventually want to perform
    const directTransaction = calculateDirectTransaction(transactionOptions, sender, destination, methodABI, params)

    if (transactionOptions.token) {
        directTransaction.pretransaction = calculatePretransaction()
        // another chunk of code
    }
    // some more code...
}
```
</details>

This does not seem to help much though, as the relationships between functions are difficult to see at a glance.

Similar to rxjs' operators, feathersjs' hooks or the cli's tasklist, we can have the functions pass a `context` object around and do some changes to it:

<details>
<summary>Solution B: declarative</summary>

```js
calculateTransactionPath = composeAsync(
  populatePermissions,
  populateDestinationApp,
  validateAppAndMethod,
  parseTransactionOptions,
  calculateDirectTransaction,
  calculatePretransaction,
  // some more code...
)

populatePermissions = (context) => {
  context.permissions = await this.permissions.take(1).toPromise()
  return context
}

parseTransactionOptions = (context) => {
  const { methodABI, params } = context
  // If an extra parameter has been provided, it is the transaction options if it is an object
  if (methodABI.inputs.length + 1 === params.length && typeof params[params.length - 1] === 'object') {
    const options = params.pop()
    transactionOptions = { ...transactionOptions, ...options }
  }

  context.transactionOptions = transactionOptions
  return context
}
```
</details>

Is much easier for a beginner to get a feel of *what* `calculateTransactionPath` does, without worrying about *how* does it do it.

If my assumptions are correct, this should:
- make something like: [return promises instead of observables](https://github.com/aragon/aragon-app-dx/issues/2) trivial
- work nicely with RxJS
- facilitate testing
- improve readability and make it easy to understand the data flow
- allow categorization by domain: app, permissions, notifications (e.g. we could have something like init, clear, acknowlege all under the same notifications umbrella), etc. and break down the main file into multiple files.

I'm not 100% sure how this will look like, but if it makes sense I can start with something small, e.g.: `postprocessRadspecDescription`.

**Comment by sohkai** [comment]
I like the structure of solution B, however, I'm a bit hesitant about sharing the state like this, since after a while it can get brittle. It's hard to know what's inside the `context` object at any given time, what adding or removing a particular step would do to the context, and what a function would expect in the context in order to run.

It'll also be difficult to strictly linearize some functionality, like calculating transaction paths, since calculating a direct transaction path may or may not short circuit the chain.

I've been thinking about breaking up some of the pieces, like the "populate", "validate", and "parse" steps into higher-order functions or "decorators", that would get applied onto a more complex logic function, but I also haven't been able to come up with a satisfying approach. It would also be nice if each of these "decorators" could avoid ordering requirements, so that each one was independent to the point of being parallelizable.

The best I can come up with right now is something multi-staged, like:

```js
async calculateTransactionPath (sender, destination, methodName, params, finalForwarder) {
  // populate
  const [destinationApp, permissions, ...] = await promise.all([
    populatePermissions(),
    populateDestinationApp(destination),
    ...
  ])

  // validate
  await promise.all([
    validateAppAndMethod(destinationApp, methodName),
    ...
  ])

  // parse
  const [transactionOptions, ...] = await promise.all([
    parseTransactionOptions(destinationApp, methodName, params),
    ...
  ])

  // The direct transaction we eventually want to perform
  const directTransaction = calculateDirectTransaction(transactionOptions, sender, destination, methodABI, params)

  if (transactionOptions.token) {
    directTransaction.pretransaction = calculatePretransaction()
    // another chunk of code
  }
  // some more code...
}
```

But it's really tricky fitting everything into the stages like that due to the data dependencies, and at this point it might as well just be single `await` statements :(.

**Comment by sohkai** [comment]
Closing; it is pretty clear `@aragon/wrapper` requires a large refactor / rewrite at this point, but we will not prioritize it in the short term.

Please reach out if you'd like to experiment with doing a refactor in this vein!
