### ISSUE TITLE
Add support for address metadata resolution and custom labels

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#251]
# THIS IS NOW OUTDATED, PLEASE SEE #253 OR THE DOCS FOR THE IMPLEMENTED API

Between `@aragon/client`, and `@aragon/wrapper`, first-class support for resolving addresses to more specific identity metadata will be added to support both [custom local labels](https://github.com/aragon/aragon/issues/602), as well as more generic identity providers.

--------

### Preamble

`AddressIdentityProvider`:
  - `AddressIdentityProvider.resolve(address: string): Promise<Object>`
  - `AddressIdentityProvider.modify(address: string, metadata: Object): Promise<???>`

`LocalLabelType`:
  - `label: string`
  - `creationDate: number (unix time)`

---------

### `@aragon/wrapper`:

- **Generic identity provider API**:
  - `Aragon.resolveAddressIdentity(address: string, providerName: string = 'local'): Promise<Object>`
    - Resolves an address' identity according to `providerName`; returned Promise resolves to an object holding metadata
    - Returned Promise rejects if provider is not installed or address is not resolvable
  - `Aragon.modifyAddressIdentity(address: string, metadata: Object, providerName: string = 'local'): Promise<???>`
    - Modifies an address' identity according to `providerName`; **not sure what returned Promise should resolve to**
    - Returned Promise rejects if provider is not installed or address cannot be modified
    - This bit may be difficult to make fully generic, given that different providers will require different interactions to write:
      - An ETH transaction
      - A web3 signature
      - A http request
      - A cache write
  - `Aragon.addressIdentityModificationIntents`: a hot observable emitting intents from apps to modify address identities
- `Aragon.requestAddressIdentityModification(address: string, providerName: string)`: emit onto `Aragon.addressIdentityModificationIntents`, so a frontend client can handle it
- A "registry" that detects and registers installed address providers, providing the routing between `Aragon.resolveAddressIdentity()` and `Aragon.modifyAddressIdentity()` to the underlying address provider
- A new RPC handler to accept resolution and modification requests

- **Local label API**:
  - A new class, `LocalLabelAddressProvider extends AddressIdentityProvider`, who gets constructed with an initialized `Cache` instance
    - Storage preamble:
      - Local labels should be saved to a global cache, perhaps as `/localAddressLabels` (a new cache instance would be created outside of any organization's)
        - Writing labels: simply a `cache.set()`
        - Resolving labels: simply a `cache.get()`
  - `LocalLabelAddressProvider.labels`: a hot observable containing `{ address: string, metadata: LocalLabelType }`; clients would subscribe to this to _observe_ the current set of all local address labels. This could be done ([similarly to how `this.notifications()` works](https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/index.js#L481, via a `.scan()` on each write request
  - `LocalLabelAddressProvider.modify(address: string, metadata: LocalLabelType): Promise<LocalLabelType>`: emit on `labels` the new label, with a `set` modifier ([similar to notifications' concept of modifiers](https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/index.js#L509))
  - `LocalLabelAddressProvider.resolve(address: string): Promise<LocalLabelType>`: use `.first()` on the `labels` observable and then do key-value lookup
  - `LocalLabelAddressProvider.clear(): Promise`: clears all the local labels

--------

### `@aragon/client`:

- `AragonApp.resolveAddressIdentity(address: string, providerName: string = 'local'): Observable<Object>`
  - Returns a single-emission observable (for sake of conforming to current API; to be later changed to a promise) with the metadata
    - If null, client should assume no address was resolved
- `AragonApp.requestAddressIdentityModification(address: string, providerName: string = 'local'): Observable<bool>`
  - Returns a single-emission observable (for sake of conforming to current API; to be later changed to a promise) with whether the request was accepted or not
  - Note that this **does not** include the metadata payload; this should only be a _request_ for a frontend to handle this modification

---------

### Misc. / Needs help

- `AddressIdentity` sounds kind of lame, but `@aragon/client` already has `AragonApp.identify()` (to identify an app's instance)
  - Any other suggestions appreciated 😄
- Do we need to include (or can we exclude) some information in `LocalLabelType`?
- `AddressIdentityProvider.modify()` and `Aragon.modifyAddressIdentity(address: string, metadata: Object, addressProvider: string = 'local'): Promise<???>` are going to be tricky and their APIs will likely not be finalized until we know about more providers and how their interactions happen
- We may want to investigate about potential memory leaks with subscriptions closing in `@aragon/client`, especially since `AragonApp.resolveAddressIdentity()` may be happening quite a lot

**Comment by 2color** [comment]
If I understand the proposal correctly, one API is for privileged interaction – for native apps in native context – and another for sandbox interaction accessible through `@aragon/client`. Additionally, there's an a we're trying to abstract the general idea of identity from local identity, we have the generic identity API. Something like the strategy pattern. 

Though I still find it confusing to follow 😅. Let's see if I can wrap head around this.

- `AddressIdentityProvider` is the interface we want identity implementation to adhere to. Providing a way to `resolve` and `modify` using promises for a consistent async interface.
- The `@aragon/client` interface can only resolve and request entering modification mode. 
- Modification is only allowed in the native context
- The `LocalLabelType` is the data structure used by `LocalLabelAddressProvider` an implementation of the `AddressIdentityProvider`. 
- `LocalLabelAddressProvider` extends the generalised provider functionality by providing a labels observable (not clear if for change events or for the full state). 

So we have two consumer types:
- iframe/sandboxed apps - `@aragon/client` -> `handler in wrapper` -> `?` -> `LocalLabelAddressProvider`. Sandboxed apps are expected to be aware of other potential identity providers while not being able to modify.
- Native apps use `@aragon/wrapper` to somehow (not fully clear) `LocalLabelAddressProvider`. 

Because we're still quite far from remote identity providers, I think we might want to consider the cost of such an arguably premature abstraction. Just based on the fact that for now, we're only going to have one single instance of the abstraction. By abstracting we might lock ourselves prematurely to a certain interface could prove inadequate given future developments etc. While  `AddressIdentityProvider.resolve(address: string): Promise<Object>` captures resolution nicely, modifications open up a myriad of scenarios that are difficult to know in advance.

**Comment by sohkai** [comment]
> * `LocalLabelAddressProvider` extends the generalised provider functionality by providing a labels observable (not clear if for change events or for the full state).

Subscribing to `LocalLabelAddressProvider.labels` would provide the entire set of local addresses on each emission. This could grow to be fairly large (imagining dumping a 1mb json file, which would be roughly 10k addresses with labels) and we may want a different strategy to obtain all of the labels set in the future.

> * iframe/sandboxed apps - `@aragon/client` -> `handler in wrapper` -> `?` -> `LocalLabelAddressProvider`

The `?` there would basically be part of the handler; each handler is created with the parent `Aragon` class injected (typically as `wrapper`), and the handler would access `Aragon.resolveAddressIdentity()` and `Aragon.modifyAddressIdentity()` directly.

> * Native apps use `@aragon/wrapper` to somehow (not fully clear) `LocalLabelAddressProvider`

They'd use `Aragon.resolveAddressIdentity()` and `Aragon.modifyAddressIdentity()` (although they would probably want to send an intent as well to gather user input; maybe `Aragon.requestAddressIdentityModification()` will be needed to do so), through the `addressProvider`, which would select the provider type (only `'local'` for now).

> By abstracting we might lock ourselves prematurely to a certain interface could prove inadequate given future developments etc.

Agreed, but we need to start somewhere 😊. Hope is to ask other people what interactions they need so we can start figuring out the `modify()` interface.

**Comment by sohkai** [comment]
Since this was initially written, we've decided to implement local labels _globally_, across all organizations visited by a client, rather than per-organization. The initial comment has been amended in addition to changes suggested from https://github.com/aragon/aragon.js/issues/251#issuecomment-468313221 and https://github.com/aragon/aragon.js/issues/251#issuecomment-468338357.

**Comment by sohkai** [comment]
During a conversation with @AquiGorka, another thing that was missed in the initial spec was a way for `@aragon/wrapper` to tell `@aragon/client` that an address has a modified identity metadata.

This is important in case the labels are changed while an app is running ([the modal appears on top of the app](https://www.figma.com/file/5QZ1KXczHAQhmTlUVDz8jv/Identity-%2F-Custom-labels?node-id=42%3A2672)), and once it's closed (via save), the `AddressBadge` should update. Another important thing is that the Preferences panel is now reachable as a modal, so [an app can still be running behind it if we import or clear the labels](https://www.figma.com/file/5QZ1KXczHAQhmTlUVDz8jv/Identity-%2F-Custom-labels?node-id=47%3A4479).

Due to this, `@aragon/client` needs a new observable that emits when these changes happen. I've been thinking that we have a few options of keys to emit:

- 'all': All addresses have modified metadata (this would only be sent on local labels being imported or cleared)
- <address>: This address has modified metadata (could happen due to any identity provider)

Any caching that the app might've done for an address' identity metadata would be revoked and need to be re-requested.

**Comment by 2color** [comment]
> Due to this, `@aragon/client` needs a new observable that emits when these changes happen. I've been thinking that we have a few options of keys to emit:

Does it need a new one? or do we include that in the response observable of 
`AragonApp.requestAddressIdentityModification`? or is that just for whether the request was accepted?

> `AragonApp.requestAddressIdentityModification()` _may_ be enough for the case where a single address gets updated; it should only emit once the action has been completed or failed, but then I'm not sure how to handle the `all` case.

Do you mean that if a modification request for an address was accepted, the app can know to make a new resolution request?

> Maybe we should only have an "update" observable and make `requestAddressIdentityModification()` return nothing?

I presume this would be part of the `@aragon/client` api. Do you see it emitting `all` or `<address>` values?

**Comment by sohkai** [comment]
> Do you mean that if a modification request for an address was accepted, the app can know to make a new resolution request?

Yes, basically. `AragonApp.requestAddressIdentityModification()` could resolve iff the modification completes successfully (kind of like when we sign transaction signatures), so the app would then know it should re-request the identity and invalidate any cached information about this identity.

I suppose an _easier_ way out for aragon/aragon would be to refresh itself or re-render the currently loaded app if you do a bulk action like importing or removing all (cc @AquiGorka). Seems like it might be a worthwhile tradeoff in terms of UX for lower API complexity (and rot).

**Comment by AquiGorka** [comment]
In my PR `aragon/aragon` is responsible for [showing the `Modal`](https://github.com/aragon/aragon/pull/630/files#diff-58eb3a8a92df759e70e120638ab834c5R88) that allows modifying a custom label.
I believe apps need only send a message to the `@aragon/wrapper` wrapper to render the Modal and wait for any of the 2 possible outcomes: `Cancel` or `Save` (modify).
If `Cancel` happens then nothing should re-render.
If `Save` happens then yes,`iframe app` should re-render. I was thinking about creating a `CustomLabels Provider/Consumer` that will abstract the subscriptions and make sure the local cache is up to date.

Having said that, let me integrate into your discussion:

> requestAddressIdentityModification() return nothing?
I'd agree with this approach, as a matter of fact, I now don't think the apps should have this as an `aragon.js` method, what the apps need to do is send an `open custom label modal with this address` message to `aragon/aragon`. (If `aragon.js` should be responsible for sending the message, I can agree with the approach, but I don't see it needs to do anything else).

> 'all': All addresses have modified metadata (this would only be sent on local labels being imported or cleared)
> '<address>: This address has modified metadata (could happen due to an identity provider)

Sounds ok. I think this is the abstraction the `provider/consumer` I talked about above should take care of, and the`iframe app`s will re-render the updated cache data.
Can we make it so that `<address>` also returns the updated meta information? This way there is no need for the extra trip to resolve it.

>I suppose an easier way out for `aragon/aragon` would be to refresh itself or re-render the currently loaded app if you do a bulk action like importing or removing all (cc @AquiGorka). Seems like it might be a worthwhile tradeoff in terms of UX for lower API complexity (and rot).

Too much no? I was thinking the `provider/consumer` could be communicating with `aragon/aragon` and update when necesarry and this changes will flow down the tree to make the `iframe app` re render.

**Comment by sohkai** [comment]
> I believe apps need only send a message to the aragon/aragon wrapper to render the Modal and wait for any of the 2 possible outcomes: Cancel or Save (modify).

> - If Cancel happens then nothing should re-render.
> - If Save happens then yes,iframe app should re-render.

If we treat `requestAddressIdentityModification()` like we do transaction intents, it would actually return a promise that could resolve iff the save happens (and rejects on cancel). This way we don't have to refresh the iframe for single modifications.

> I was thinking about creating a CustomLabels Provider/Consumer that will abstract the subscriptions and make sure the local cache is up to date.

Had a conversation with @2color about this, and we were thinking aragon.js could hold this cache (it would be modified or wiped if we had a `'all'`-type event) so that the cache is useful across apps.

Rather than a specific `CustomLabels` provider/consumer, I was thinking we could instead build a provider/consumer for all _identity resolution_, that basically just hides the logic of `wrapper.resolveAddressIdentity()` and `wrapper.modifyAddressIdentity()` away from `IdentityBadge`s.

> I agree with this approach, as a matter of fact, I now don't think the apps should have this as an aragon.js method, what the apps need to do is send an open custom label modal with this address message to aragon/aragon. (If aragon.js should be responsible for sending the message, I can agree with the approach, but I don't see it needs to do anything else).

We should prefer to use `aragon.js`'s notion of rpc-messengers, rather than the native `postMessage()` API. There may be some cases where we can't avoid it, but for this case, it fits really nicely into the current message passing framework. This allows the apps to be immediately generic from custom labels with very little cost; they shouldn't care that the identity is a custom label, they just care it was able to resolve to some metadata.

> Can we make it so that <address> also returns the updated meta information? This way there is no need for the extra trip to resolve it.

Assuming we don't have a new observable and instead return values in `wrapper.resolveAddressIdentity()`,  this should be possible (worst case the provider could do another fetch itself when the modification is finished to provide this information).

> Too much no? I was thinking the provider/consumer could be communicating with aragon/aragon and update when necesarry and this changes will flow down the tree to make the iframe app re render.

Yep, refreshing the iframe (if we're on it) should be enough.

**Comment by sohkai** [comment]
Was just thinking—we'd probably want the `IdentityProvider.resolve()` to conform to a standard schema type that corresponds to the degrees of freedom available in `IdentityBadge` (e.g. providerName, title, popoverAction, image).

**Comment by 2color** [comment]
For the initial implementation which includes just local identity the following `metadata` object schema will be used:

```
{
  name: <string>
  createdAt: <unixtimestamp>
}
```

We may want to expand this later. But for now these should the bare minimum. 

This will form the basis for the `IdentityProvider.resolve()` schema as @sohkai noted.

**Comment by 2color** [comment]
> Due to this, @aragon/client needs a new observable that emits when these changes happen. I've been thinking that we have a few options of keys to emit:
> 'all': All addresses have modified metadata (this would only be sent on local labels being imported or cleared)
> `<address>`: This address has modified metadata (could happen due to any identity provider)

Yeah that was added to the draft implementation.

> If we treat requestAddressIdentityModification() like we do transaction intents, it would actually return a promise that could resolve iff the save happens (and rejects on cancel). This way we don't have to refresh the iframe for single modifications.

Yep. That's simple enough and solves the case of a single modification. Probably worth implementing. 


> Rather than a specific CustomLabels provider/consumer, I was thinking we could instead build a provider/consumer for all identity resolution, that basically just hides the logic of wrapper.resolveAddressIdentity() and wrapper.modifyAddressIdentity() away from IdentityBadges.

So many different types of providers that we have already. 
Do you mean a React provider/consumer?
In privileged context (aragon/aragon) or iframe apps? 

This is a nice idea. Though in the current implementation in `aragon/aragon`we rely on a react provider/consumer that provides the full identities object. But I can see how this would be a nice abstraction in iframe apps.

**Comment by sohkai** [comment]
> Do you mean a React provider/consumer?

Yes, one that other app developers could use seamlessly in their own Aragon apps, so that they wouldn't have to worry about implementing all the hooks and plumbing to use the information from identity providers.

I would target iframe apps, since the native apps in aragon/aragon have access to a lot more information.

**Comment by sohkai** [comment]
On discussing and reviewing https://github.com/aragon/aragon.js/pull/253, a few more ideas have cropped up:

- Caching for identity providers
  - I think it would make most sense for each identity provider to build their own internal cache of resolved profiles (or resolution attempts), so that the interface for resolving addresses is still just `resolve()`.
  - Cache invalidation and request throttling in each identity provider can be customized themselves as needed (e.g. for an ENS provider, it would only make sense to refresh if at least 15s passed due to block times)
- Provider priority
  - **In the future**, when it becomes possible to install multiple providers, it would be ideal if `@aragon/wrapper` transparently handled resolutions and modifications by selecting the highest priority resolver.
  - However, this means it'll have to know which provider to send modification requests to. This may be tricky, as it requires us to know which provider is currently being used for a particular address (if the address is being resolved with an ENS identity provider, the user would want to modify ENS, not the local label). We could add a small cache that maps an address to its most recently used provider, but the implications will need to be thought through more.

**Comment by 2color** [comment]
### Caching for identity providers

> I think it would make most sense for each identity provider to build their own internal cache of resolved profiles (or resolution attempts), so that the interface for resolving addresses is still just resolve().

Yes. Since resolve is already asynchronous this is natural. I think it makes sense to encapsulate caching logic with the provider, because every identity solution has it's own assumptions. Imagine using something naïve like DNS TXT record to map addresses to DNS names. The caching invalidation would probably correlate to the TTL of the records.

> Cache invalidation and request throttling in each identity provider can be customized themselves as needed (e.g. for an ENS provider, it would only make sense to refresh if at least 15s passed due to block times)

👍

### Provider priority
> In the future, when it becomes possible to install multiple providers, it would be ideal if @aragon/wrapper transparently handled resolutions and modifications by selecting the highest priority resolver.

From a UX perspective this might be tricky. Especially if provider details are unknown to the apps.  How do users know where this resolution is from? 
What if an app wants to tie its implementation to a specific identity provider?
Are we assuming that the user chooses the identity provider? it could play differently in the future, e.g. the apps/app developers would make choice of provider that fits the application best.
This came up during [Aragon All Devs](https://docs.google.com/document/d/13AFoD-jvSXaJUP8iktprQrPeW-D7xrLlOMJWTUcAqEs).

> However, this means it'll have to know which provider to send modification requests to. This may be tricky, as it requires us to know which provider is currently being used for a particular address (if the address is being resolved with an ENS identity provider, the user would want to modify ENS, not the local label). We could add a small cache that maps an address to its most recently used provider, but the implications will need to be thought through more.

I agree it's a little tricky. This is also contingent on how the identity provider priority is determined and if there's a need for an app to affect/influence priority.

**Comment by sohkai** [comment]
> How do users know where this resolution is from?

The "badge" that's inside the `IdentityBadge`'s popover will hopefully provide enough information (it should probably match the name that's visible in the priority selector)

> What if an app wants to tie its implementation to a specific identity provider?

I'd also say that this shouldn't be recommended... identity for addresses seems like something we should abstract completely from app developers. I hold the opinion that the concept of identity is something that comes the _user's_ perspective.

> Are we assuming that the user chooses the identity provider? it could play differently in the future, e.g. the apps/app developers would make choice of provider that fits the application best.

My assumption in the future is an organization will supply a default priority list, and the user could override it.

**Comment by sohkai** [comment]
Closing for #253.
