### ISSUE TITLE
Migrate from ethjs-ens to ethereum-ens or web3.js

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#254]
We should also do this for apm.js. `ethjs-ens` is still relying on older web3 versions, whereas `ethereum-ens` has upgraded this (despite the fact that they might not fully support `web3@1.0.0` yet...).

**Alternatively**: we could use web3.js' built-in ENS resolution (assuming it can take custom root registry addresses).

**Comment by 2color** [comment]
From https://docs.ens.domains/dapp-developer-guide/ens-libraries#which-javascript-library-should-i-use

> If you are already using web3.js, and do not require functionality such as creating subdomains, transferring ownership, or updating resolvers, use web3.js's ENS support.

The only place where we use it seems to be https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/ens/index.js#L19

**Comment by sohkai** [comment]
Ah ha, good point. We should try that out once we've also upgraded web3.

**Comment by sohkai** [comment]
It turns out that [web3.js does not support setting custom ENS registries](https://github.com/ethereum/web3.js/issues/3010) (which we need on Rinkeby, since we use our own deployed ENS instance).

Will monitor progress on web3, but we can also look into integration something like [ens-lite](https://github.com/jefflau/ens-lite).

**Comment by sohkai** [comment]
See #422; we should be able to use web3.js@latest now.
