### ISSUE TITLE
Wrapper: Allow URL routers in apps

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon.js#258]
Apps are sandboxed in an iframe and can't change browser's history. If a URL router is used inside an app, it changes the url of the inner page, but not the url at the browser level, so the url can't be shared.

React router example:
```jsx
<HashRouter>
  <Switch>
    <Route exact path="/" component={Home} />
    <Route path="/about" component={About} />
    <Route component={Whoops404} />
  </Switch>
</HashRouter>
```

I propose the Wrapper to:
1. Provide a function so an app can update the browser's location. For example: `provider.updateUrl('/about/me')` updates the url to `http://localhost:3000/#/<dao-addr>/<app-addr>/about/me`
2. Change the inner page URL when the browser url is modified. For example: `http://localhost:3000/#/<dao-addr>/<app-addr>/about/me` should load the following URL in the iframe: `http://localhost:8080/ipfs/<ipfs-hash>/#/about/me`.

**Comment by sohkai** [comment]
Originally I think we wanted to use app contexts to handle this, but the Aragon client currently doesn't handle any contexts. We also started using url params in some of the native applications, like Permissions, to encode URL paths.

But curious what you think about this @bpierre?

**Comment by sohkai** [comment]
> Provide a function so an app can update the browser's location. For example: provider.updateUrl('/about/me') updates the url to http://localhost:3000/#/<dao-addr>/<app-addr>/about/me

This is now possible with the `paths()` API that was added in https://github.com/aragon/aragon.js/pull/352.

> Change the inner page URL when the browser url is modified. For example: http://localhost:3000/#/<dao-addr>/<app-addr>/about/me should load the following URL in the iframe: http://localhost:8080/ipfs/<ipfs-hash>/#/about/me.

It's unclear if this is still needed; in particular we may be able to customize routing libraries so they work with the `paths()` API than relying on the inner page's URL.

**Comment by sembrestels** [comment]
Since the `api.path()` function returns a multi-emission observable, I think that second part is not needed to be covered by the API. Since both behaviours I was requesting are covered with the new API, I proceed to close this issue. Feel free to reopen if needed.
