### ISSUE TITLE
API: migrate to promise-based returns for single-emission responses

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#264]
In `@aragon/api`, we currently return an observable whenever we expect a value back from `@aragon/wrapper`. However, many of these observables only emit a single value, and force an awkward programming model for most programmers.

What we could do:

1. Adopt the rxjs nomenclature and have every method returning an observable have the `$` suffix
1. Name a method plural (`s` suffix) to denote observables and singular to denote promises

And then release a new `v3.0.0` version of this package.

Of the two, I think 1 is most the approachable and clear. Perhaps the only awkward change is `app.store()`, but I don't really think we even need to return an observable here (what could someone want to do with the resulting state that they didn't already do in the `store()`'s handler?).

cc @2color @0x6431346e

**Comment by 0x6431346e** [comment]
What are the benefits of this? Is the aim to improve the UX for devs non-familiar with RxJS?

**Comment by sohkai** [comment]
That's the main one, yes.

We commonly do the equivalent of `app.func().toPromise()`, which is confusing / annoying, and a single emission observable is honestly better represented as just a promise. RxJS also takes in promises fairly transparently; anywhere you can give an observable you can also give a promise.

**Comment by 2color** [comment]
Great idea. 

> Adopt the rxjs nomenclature and have every method returning an observable have the $ suffix

👍

The subtle difference between singular and plural denoted by the `s` is easy to miss. The $ suffix is really helpful for such cases.

**Comment by sohkai** [comment]
Closing; we will re-evaluate the external API in the future.
