### ISSUE TITLE
@aragon/wrapper using events and promises

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon.js#265]
After talking with @osarrouy about CLI extensions, it might make sense to create a package like `@aragon/api-evented` (#230), but for the wrapper, to improve the UX for cli devs, in the case where they would be using the wrapper lib directly.

An alternative would be a set of utilities (also on top of rxjs), something like:
`getAppsForDao(address)`
`getPermissionsForDao(address)`
`executeTx(dao, app, function, args)`
etc., so that we don't replicate this code in all the extensions:
```
           const tryFindTransactionPath = async () => {
              if (appsLoaded && wrapper) {
                try {
                  ctx.transactionPath = await getTransactionPath(wrapper)
                  resolve()
                } catch (e) {
                  reject(e)
                }
              }
            }

            initAragonJS(dao, apm['ens-registry'], {
              provider: wsProvider || web3.currentProvider,
              accounts,
              onApps: async apps => {
                appsLoaded = true
                await tryFindTransactionPath()
              },
              onError: err => reject(err),
            })
              .then(async initializedWrapper => {
                wrapper = initializedWrapper
                await tryFindTransactionPath()
              })
```

**Comment by sohkai** [comment]
In many ways this seems like what `aragonjs-wrapper.js` already does in both the CLI and aragon/aragon; perhaps we could bake that in as a package?

**Comment by 0x6431346e** [comment]
> In many ways this seems like what `aragonjs-wrapper.js` already does in both the CLI and aragon/aragon; perhaps we could bake that in as a package?

Yes!

We could also release it as another module in the wrapper package: `@aragon/wrapper/helpers` so that we don't need to install/update another package.

**Comment by sohkai** [comment]
Exposing a better interface for API integrations with Aragon organizations will be done with the toolkit efforts in the SDK.
