### ISSUE TITLE
Give apps more information about the organization

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#272]
We could create an API that returns some useful information about the organization an app is installed on, including:

- Its initial creator
- Which template it was created from (if any)
  - If this app was created by the template (rough check using the `initializationBlock`)

This would allow apps like the Token Manager to respond better in multisig organizations, so it can show more useful UI relevant to how it should be used.

**Comment by 0xGabi** [comment]
Make sense to include the initialization parameters of the app (or/and current parameters)?

**Comment by 2color** [comment]
Can you elaborate on how we'd know which template it was created with. 
For example the `a1.aragonid.eth` DAO has the following address: `0x635193983512c621E6a3E15ee1dbF36f0C0Db8E0`. How do we know which template was used for iut?

**Comment by sohkai** [comment]
> Make sense to include the initialization parameters of the app (or/and current parameters)?

The parameters to `initialize()` would be really difficult to get, since they're not saved as state.

> How do we know which template was used for iut?

Will have to do a bit of digging to see if there's a reliable way of getting this with just events, but there are a couple ways to get this info (worst one being to add some state in the templates).

But this brings up a good point, in that this would likely only work with a short-listed set of templates that we check against.

**Comment by sohkai** [comment]
Closing for now; this API is fairly difficult to accomplish and not that valuable.
