### ISSUE TITLE
Implement notifications

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#30]
Notifications are sent to the wrapper in the following format:

```js
type Notification = {
  id: string,
  appId: string,
  timestamp: number,
  title: string,
  body: string,
  context: ?any
}
```

The `title`, `id` and `appId` properties are provided by `node-aragon`, not the wrapper or the client.

The RPC call for the applications is as follows:

```js
type NotificationCall = {
  id: string,
  jsonrpc: '2.0',
  method: 'notification',
  params: [number, string, ?any]
}
```

Where the first parameter is the UNIX timestamp of the notification, the second parameter is the  notification `body` and the third (and optional) parameter is the notification `context`.

When a notification is clicked, the wrapper should perform the following steps

- Load the application instance
- If the notification has a `context` that is not `null` or `undefined`, then the following JSONRPC request should be sent to the application. The wrapper should not expect a response from the application.

```js
type NotificationContextCall = {
  id: string,
  jsonrpc: '2.0',
  method: 'context',
  params: [any]
}
```

Where the first parameter is the `context` of the notification.

**Comment by izqui** [comment]
We should add a 'timestamp' value to the notification, as they could have originated while the client wasn't open.

In most cases the timestamp will be the timestamp of the block in which the event was fired.

**Comment by onbjerg** [comment]
@izqui True, added.
