### ISSUE TITLE
API: check connected account's network

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#300]
It would be a breaking change, but `app.accounts()` may be the best place to put this information.

Alternatively, there could be another method, e.g. `app.connectedAccountNetwork()`.

**Comment by emaG3m** [comment]
Thanks!!! 💯 💯 💯

**Comment by 2color** [comment]
I also think it belongs to `app.accounts`. 

Accounts' abstraction is leaky. Part of it is implemented in [@aragon/wrapper](https://github.com/aragon/aragon.js/blob/app-state-caching/packages/aragon-wrapper/src/index.js#L207) and part of it in [argon/aragon](https://github.com/aragon/aragon/blob/master/src/aragonjs-wrapper.js#L376).

@sohkai Can you explain the logic there?

**Comment by sohkai** [comment]
@2color The main thing is that we initialize `@aragon/wrapper` with the "read-only" web3 provider, but we need the account from the user's "write" (wallet) web3 provider.

The rationale behind this originally was that the wallet web3 provider (e.g. metamask) can be very very slow (to the order of >20min to reduce the initial ACL).

**Comment by 2color** [comment]
> The main thing is that we initialize @aragon/wrapper with the "read-only" web3 provider, but we need the account from the user's "write" (wallet) web3 provider. 

That's clear! Thanks for clarifying that.

> because web3 doesn't expose an event when the account or network change, we're forced to poll for them (account, network).

I understand. 

> The rationale behind this originally was that the wallet web3 provider (e.g. metamask) can be very very slow (to the order of >20min to reduce the initial ACL).

Interesting. Is that because of the Web3.js version that metamask uses? Or the actual node that it connects to?

**Comment by sohkai** [comment]
> Is that because of the Web3.js version that metamask uses? Or the actual node that it connects to?

Metamask uses infura by default, but they likely do some throttling themselves (since everyone using metamask is piggying backing off of metamask's infura key). Haven't tried doing this recently in the last six months, but I would still assume it's still not very reliable.

**Comment by sohkai** [comment]
Closing for #237.
