### ISSUE TITLE
API to approve ERC20 on a different contract / context

### ISSUE THREAD

**Issue by osarrouy** [aragon/aragon.js#309]
We have a use case with the Aragon Fundraising [Apiary] app where we would need to use the `token` pretransaction hook to approve another contract than the app one.

This is because with the fundraising app users interact with a `Controller` or `API` contract itself relying on other contracts [such as the `MarketMaker` contract]. The contract which will actually move the token is not the `API` one - the one users interact with - but the `MarketMaker` one. So we would need to approve the `MarketMaker` contract from the `API` frontend ...

We can not release the Fundraising app without this feature so .... I would say it's urgent ;)

**Comment by osarrouy** [comment]
@2color @0x6431346e Any news about that ? Cause if we don't have that API we're basically stuck for apiary :(

**Comment by luisivan** [comment]
Pretty urgent, can you guys @2color @0x6431346e take a look? :pray:

**Comment by 2color** [comment]
I did a naive implementation in https://github.com/aragon/aragon.js/pull/321. @osarrouy Have a look and let me know what you think.

**Comment by osarrouy** [comment]
It looks all good to me [though I can't officially 'review' the PR cause I dont' have the permission to do so].
