### ISSUE TITLE
Emit errors in RPC messenger when an error response is received

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#31]
Whenever a response is received in the RPC messenger (`src/rpc/Messenger.js`) and it is an error, then an error should be emitted on the observable as opposed to just passing it through as a normal response.

The responses and errors conform to the JSONRPC 2.0 spec.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x33563dd2e0c2d12656b7a480f587dcb6458fa41a125b6f56ab148c6979b832cf](https://etherscan.io/tx/0x33563dd2e0c2d12656b7a480f587dcb6458fa41a125b6f56ab148c6979b832cf)

**Comment by sohkai** [comment]
Closed by #277, although I've let multi-emission observables "survive" errors for now.
