### ISSUE TITLE
Use Flow

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#33]

**Comment by Quazia** [comment]
Probably not the direction we'll go with this if flow won't be open. Maybe using zenhub more could be used in place of this but I don't think it needs it's own issue?

**Comment by john-light** [comment]
@Quazia this is not in relation to the Flow task management tool.

**Comment by bpierre** [comment]
Yes this is about the [type checker](https://flow.org/) that [Aragon.js is using](https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/package.json#L7) now: we can close this issue.
