### ISSUE TITLE
Separate client and wrapper

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#37]
Since the client (for applications) is very small (1 file with 2 imports) and the wrapper is considerably bigger than the client, we should probably separate the two to reduce bundle size and separate the code in a meaningful manner.

I don't think this is top priority right now, so I've scheduled it for the next version.

My thinking is that applications would import `@aragon/client` or something similar and wrappers would import `@aragon/wrapper`.

**Comment by onbjerg** [comment]
Thought @izqui @harshjv @bpierre?

**Comment by izqui** [comment]
I agree on it not being a top priority, but not having to bundle the wrapper code in every single app is a good idea

**Comment by onbjerg** [comment]
Fixed in rewrite branch
