### ISSUE TITLE
i need you advice

### ISSUE THREAD

**Issue by mikearagon2019** [aragon/aragon.js#399]
Good afternoon. Tell me, please.
https://rinkeby.autark.xyz/#/testleo
Here they work. How to make it work on the mainet
https://mainnet.aragon.org/#/mars-dao.eth/0x332558d582d6ca70762917a52b5f0b4268d68a5c

**Comment by sohkai** [comment]
Hey @mikearagon2019, Open Enterprise has not been released yet on mainnet (it's coming in the next few days after their rinkeby beta). Please sit tight until then, and use the rinkeby version to test!
