### ISSUE TITLE
Allow listening to arbitrary events emitted by addresses other than the proxy

### ISSUE THREAD

**Issue by izqui** [aragon/aragon.js#41]
Some apps need to get events from other addresses, for example the TokenManager app doesn't emit events on token transfers because the managed token already emits them.

This should also allow to pass a filter to take advantage of indexed event logs.

**Comment by onbjerg** [comment]
My only fear with this is that people will listen to other apps (i.e. by listening to the kernel proxy) and then make fake apps. I guess curated application registries would solve this anyway.
