### ISSUE TITLE
Wrapper: Enable ACL intents in apps

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon.js#417]
Calling some ACL functions from inside an app don't work, for example:
```js
const aclHandler = api.external(aclAddr, aclAbi)
aclHandler.revokePermission(entity, app, role).toPromise()
```
Doesn't find a transaction path because `revokePermission` have not an `auth()` modifier (it has an `onlyPermissionManager()` modifier instead).

I propose to change the behavior of the [`intent` handler](https://github.com/aragon/aragon.js/blob/b94f002b28ab9f021e1bd3db690e049a3841451c/packages/aragon-wrapper/src/rpc/handlers/intent.js) so it does a [`performACLIntent()`](https://github.com/aragon/aragon.js/blob/b94f002b28ab9f021e1bd3db690e049a3841451c/packages/aragon-wrapper/src/index.js#L1230) if needed.

**Comment by sohkai** [comment]
Good catch, @sembrestels, this should be fairly easy to detect in the intent handler, or we could wrap the ACL detection into `performTransactionPath()` (we've had to previously fix this behaviour for intent baskets, so this is the third time we've forgotten to properly detect ACLs paths 😅).
