### ISSUE TITLE
Use `ethereum-ens`

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#42]
There's no reason we should manually maintain ENS-specific code if there exists a good and minimal library for it.

**Comment by izqui** [comment]
I was unaware that the library allowed to provide an arbitrary ENS registry address https://github.com/Arachnid/ensjs/blob/master/index.js#L406. Lets totally do this

**Comment by onbjerg** [comment]
Just leaving a quick note here: we already did this in `aragon-dev-cli` on the refactor branch. It's pretty much a copy/paste at this point.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xeb3d2c2cf2675f8931af9ae6d596cafeeaf2b02c8de81436e0ef43475b5bc7ef](https://etherscan.io/tx/0xeb3d2c2cf2675f8931af9ae6d596cafeeaf2b02c8de81436e0ef43475b5bc7ef)

**Comment by onbjerg** [comment]
Not relevant
