### ISSUE TITLE
Allow to make calls and send transactions to contract addresses other than the AppProxy

### ISSUE THREAD

**Issue by izqui** [aragon/aragon.js#43]
Related to #41.

Apps that interact with contracts outside an Aragon organization need the ability to make calls and transactions to other contracts. The most obvious example is apps that work with tokens (such as the Token Manager or Finance) which depend directly on the tokens to fetch balances. Another example is the Fundraising app, in which buyers need to interact with their tokens in order to buy in sales.

In the case of sending transactions, it should be handled differently than current 'intents' and allow to perform the action directly without calculating any fwd path. The signer in the wrapper should let the user know it is not a 'normal action' being performed and it could have consequences. In the case of known actions such as token transfers, we would be able to provide a description for it.

**Comment by sohkai** [comment]
From #75:

> It would also be nice to have a way to get an event stream from another contract. Even better if this was somehow integrated into the store() (e.g. upon initializing the store, you provided an array of other event streams that were then merged with the app contract's events).

**Comment by sohkai** [comment]
Closing for #120 (send-support), as #76 has implemented read-support.
