### ISSUE TITLE
Example usage?

### ISSUE THREAD

**Issue by et** [aragon/aragon.js#52]
Is there an example of using this with an Aragon contract? Ideally, an integration with something [here](https://github.com/aragon/aragon-apps) would be very helpful.

**Comment by sohkai** [comment]
They'll be coming soon to aragon-apps; we're working on them!

**Comment by et** [comment]
Thanks @sohkai. Is it possible to demonstrate a minimum version? One that just makes a call to a contract.
For what it’s worth, my set up is a truffle deploy to a local parity node.
I’m trying to use this for the ETHDenver hackathon so this request is sorta time dependent 😉

**Comment by onbjerg** [comment]
@et Hi! The README has a usage example. To actually run it though, you need to load it inside of a wrapper. I have a small development wrapper I could share with you before the final wrapper is done. Whereabouts are you located?

Also, sorry for the late response, this hackathon is crazy full with people, so the WiFi has not worked for me at all up until this point.

**Comment by et** [comment]
Hi @onbjerg. Thanks for you reponse and no worries about the timeliness. We took the basic model and were able to mold it into a slightly different governance platform that fit our needs. Hopefully, we'll get to demo it to you all tomorrow 😄

**Comment by onbjerg** [comment]
@et Hey, thank you for the demo at the hackathon!

I'll close down this issue, but I've added better docs and DX on the top of my list. Going to implement a lot of changes based on the invaluable feedback we got at the hackathon.

**Comment by et** [comment]
Awesome! Thank you 👍
