### ISSUE TITLE
Naming change: 'cache' -> 'store'

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#56]
From discussions with @bpierre:

`cache` sounds more like an optional optimization feature, for non-persistent storage.

`store` (or `state`?) maps better to the flux / redux naming pattern, and may be more obvious for new developers coming in.

**Comment by onbjerg** [comment]
The cache is optional. It's not really a store as in Redux or Flux, since you do not dispatch actions directly on the cache, it's only CRUD.

**Comment by sohkai** [comment]
Maybe `state` is a better term then, since both `store` and `cache` seem to be confusing?

**Comment by onbjerg** [comment]
But I disagree - it is a cache. It's storage of the result of some computation in order to speed up load times, which (at least for me), is what a cache is

**Comment by izqui** [comment]
I like `state`, but agree with @onbjerg that this is a cache since you could compute this every time but it would suck.

**Comment by luisivan** [comment]
¯\_( ͡° ͜ʖ ͡°)_/¯

**Comment by sohkai** [comment]
It is technically a cache, but we use it for propagating state (as messages) to the apps' frontends.

The confusion comes from what it "technically" is, vs. how it's "meant" to be used (as a design pattern for frontends).

**Comment by onbjerg** [comment]
It is pretty much the same as having 2 servers using the same Redis instance for cache. Doesn't mean it is not a cache.

I honestly think calling it state would be even more confusing

**Comment by sohkai** [comment]
Closing since we're not likely to make this naming change at this point.
