### ISSUE TITLE
Sandboxing cache

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#57]
As it stands, the cache can be arbitrarily read / set by any app, since the app decides what key to pass in. Read is not a huge deal, but modifying is.

We should sandbox the cache so that apps can only interact with their sections (e.g. prefixing the keys with the app proxy's address and not allowing cache actions across prefixes?).

If we closed off read access with this sandbox, we would additionally require a whitelisting capability. This would allow an app / wrapper to register itself as readable / writeable across different apps. A use case of this would be the Settings app, where other apps will likely need to have read access to the settings.

**Comment by onbjerg** [comment]
@sohkai This is already done.

https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/rpc/handlers/cache.js#L2
