### ISSUE TITLE
Save latest block in cache

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#6]

**Comment by izqui** [comment]
https://github.com/aragon/node-aragon/blob/7cbd7ea069ca055023490d6d47edabb02baffb58/src/core/Proxy.js#L33-L37

Fetching events from block 0 is going to be a huge performance issue when run in a blockchain that has millions of blocks. The initial load should be made from [initializationBlock](https://github.com/aragon/aragon-core/blob/dev/contracts/common/Initializable.sol#L20) and then cache what was the last block number in which state was stored (so in case the operation is interrupted, we know where to restart).

**Comment by onbjerg** [comment]
@izqui Done in 5de1463

**Comment by sohkai** [comment]
Superseded by #297.
