### ISSUE TITLE
Add a way to get the addresses the user controls

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#62]
This might be good for *directed notifications*, i.e. notifications that are only pertinent to a single user. Other use cases probably.

**Comment by sohkai** [comment]
One big use case is in the frontend to change the UI based on the user's account (e.g. they're a token holder). We can do that by using the cache, but that gets pretty messy.

**Comment by onbjerg** [comment]
@sohkai for that, the wrapper can already get the user addresses. I am referring to apps.

For the wrapper:

```js
wrapper.getAccounts() // => Promise<Array<String>>
```

**Comment by sohkai** [comment]
Oh sorry, I was referring to apps as well (e.g. the Token Manager).

**Comment by sohkai** [comment]
Just realized we could do this really easily with another RPC handler that proxies to `wrapper.getAccounts()` and a client method :).

**Comment by onbjerg** [comment]
yep
