### ISSUE TITLE
Cache transaction index in addition to block number 

### ISSUE THREAD

**Issue by izqui** [aragon/aragon.js#63]
For event processing caching only the block number is not enough as the client can be disconnected in the middle of processing a given block. 

In the context of block reorg, we should maybe also cache all the processed txids in a given block and revert those if we detect the ordering ever changing, but this is a whole other can of worms

**Comment by sohkai** [comment]
Another idea is to debounce writes to the cache until a block is fully processed, so that the state of the cache is always at the end of a block.

**Comment by sohkai** [comment]
Superseded by #297.
