### ISSUE TITLE
Wrapper should error if the provided address isn't a DAO

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#64]
Otherwise, the app breaks because `this.kernelProxy.call('acl')` returns `0x0` and web3 complains it can't make an ACL out of that.

@bpierre we should detect the thrown error and display a "No organization found" screen or similar.

**Comment by sohkai** [comment]
Best way ATM is to check if the kernel's ACL is non-zero, but in the future we might provide a `function isKernel() pure returns (bool)` interface in the kernel to make this more absolute.

**Comment by chris-remus** [comment]
@sohkai to pick this up.
