### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by prahaladbelavadi** [aragon/aragon.js#8]
Readme.md links an absolute path to contributing.md but there isn't a contributing.md file in repository

**Comment by onbjerg** [comment]
Yes, this is a work in progress 😊

**Comment by prahaladbelavadi** [comment]
Update: There happens to be a contributing.md [here](https://github.com/aragon/aragon.js/blob/master/CONTRIBUTING.md) that was committed on May 11th and the readme has an update linking the contributing,md by @Smokyish .

Pending addition to CLI by @Quazia  this issue can be closed.

Readme commit: https://github.com/aragon/aragon.js/commit/2e728f1b7ef3a4921e0b67d719de78984d9f33f2#diff-04c6e90faac2675aa89e2176d2eec7d8
Contributing Commit: https://github.com/aragon/aragon.js/commit/b2ab7b861a496896a76db9c590a93a5f24ddf2ff#diff-6a3371457528722a734f3c51d9238c13
