### ISSUE TITLE
Implement caching on the filesystem

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#81]

**Comment by sohkai** [comment]
From https://github.com/aragon/aragon.js/pull/238

> In general, we need a smart way to detect when the underlying chain changes (`--reset`) and invalidate the entire cache.

We can likely do this by detecting the block number (once we have block caching) and reseting it if it ever goes below what we've cached.

**Comment by sohkai** [comment]
Closing this; caching on the filesystem is not very useful in light of other server-side solutions for reducing application state.

If one _really_ wanted to, they could write a wrapper above `@aragon/wrapper` that just persists the cache to a json file / etc.
