### ISSUE TITLE
Wrapper <-> Client ready handshake

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#83]
We're currently doing this on haphazardly by using the native APIs in the wrapper and clients, but it'd be nice if aragon.js did this automatically on initialization.

Ideally, as soon as an aragon.js client is finished instantiating, it would send a "ready" message to the wrapper, which would respond with its own "ready" message. The client should also expose a `.ready()` observable that completes when the response from the wrapper is received.

**Comment by onbjerg** [comment]
Alternatively we could queue up RPC messages until the ready message is received by either, e.g. if the wrapper wants to send an app context, but it hasn't yet received the ready signal from the app, that message will just be queued up in @aragon/messenger and sent when it has. Same goes for communication from app -> wrapper.

Thoughts?

**Comment by sohkai** [comment]
Absolutely, the messenger should queue messages until it receives a ready!

**Comment by sohkai** [comment]
This has mostly been alleviated by doing the required handshake at the application layer, and via `api-react`.

The only thing that we could improve is writing better docs on how this works, but is a separate issue altogether (the docs in general need love).
