### ISSUE TITLE
Add method to check current sync state for apps

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#86]
Expose some sort of function that compares the current block height to the cached cursor (see #85 for an explanation of cursors), giving an estimate of how much the app is synced.

**Comment by bpierre** [comment]
Related: https://github.com/aragon/aragon.js/issues/331

**Comment by sohkai** [comment]
Closing; #297 addressed some of these problems (you can tell if you're syncing) and #331 would be able to provide incremental progress.
