### ISSUE TITLE
Add ability to set available accounts

### ISSUE THREAD

**Issue by sohkai** [aragon/aragon.js#91]
We're currently using two different instances of web3 (metamask provider for accounts, another for aragon.js events), so aragon.js doesn't know the real accounts of the user.

It'd be nice if we could manually set this on the wrapper; if it hasn't been set, it should default to its own `web3.eth.accounts`.

Breaks transaction pathing on the client :(.

**Comment by onbjerg** [comment]
Great catch, will fix
